### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by traneric94** [traneric94/p5000x#2]
- [x] Backend: database, model, controller, views

- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Smooth, bug-free navigation
- [x] Styling
- [x] Adequate and appropriate seeds

**Comment by ryan-mapa** [comment]
- [ ] Clear errors
- [ ] Demo login
- [ ] form styling (centering, button width... etc)
- [ ] Navbar button styling changes

**Comment by ryan-mapa** [comment]
Nice work! Looks all good! Some funny nav bar styling and things, but those aren't strictly related to auth.
